# Python Basics and Binary Classification for Neuroscience

## 1. Introduction to Python Basics

### 1.1 Variables and Basic Operations

# In Python, we can store values in variables and manipulate them with math.
# Scroll over the cell below and click the "play" button that appears on the left or click the cell and press Shift+Enter to execute the code (It will take a second for Google to spin up a cloud computer for your code)

In [ ]:
x = 5
y = 3

# We can perform basic arithmetic operations
print(f"Addition: {x + y}")
print(f"Subtraction: {x - y}")
print(f"Multiplication: {x * y}")
print(f"Division: {x / y}")

# We can store the result of an operation in a new variable

z = x + y
print(f"The value of z is {z}")

Addition: 8
Subtraction: 2
Multiplication: 15
Division: 1.6666666666666667
The value of z is 8


# Exercise 1: Create two variables with different values and print their product (1 minute)


In [ ]:
# Enter code below this line to solve the exercise


### 1.2 Lists and For Loops



In [ ]:
# Lists are ordered collections of items

numbers = [1, 2, 3, 4, 5]

# We can iterate through lists using for loops
for num in numbers:
    print(num)

1
2
3
4
5


In [ ]:
# Loops are important ways to organize and execute your code efficiently

numbers_result = []
for num in numbers:
    numbers_result.append(num * 2)

print(numbers_result)

[2, 4, 6, 8, 10]


In [ ]:
# Lists can be accessed and changed by indexing them

print(numbers[0])
numbers[0] = 10
print(numbers)

1
[10, 2, 3, 4, 5]


# Exercise 2: Lists can carry words, or "strings" as well as numbers. Create a list of your favorite colors and use a loop to print the list in reverse order

In [ ]:
# To assign a string to a variable, type the string and surround it with quotes
x = "red"
# Many python variables have in-built functions which help us out, for example:
length_of_list = len(numbers)
print(length_of_list)

5


### 1.3 Functions


In [ ]:
# Functions help us organize and reuse code
def greet(name):
    return f"Hello, {name}!"

print(greet("Neuroscientist"))

Hello, Neuroscientist!


# Exercise 3: Write a function that takes a list as input and returns its square. Execute this function on the variable "numbers" above.

## 2. Introduction to NumPy and Pandas. These are near-ubiquitous "packages," unofficial libraries of code that are universally used for matrix math and data management


In [ ]:

# First, let's import the libraries - now we can use the functions inside numpy by using the form np.something or
import numpy as np
import pandas as pd

### 2.1 NumPy Arrays

# NumPy arrays are efficient for numerical operations
arr = np.array([1, 2, 3, 4, 5])
arr2 = np.array(numbers)
print(f"Array: {arr}")
print(f"Mean of array: {np.mean(arr)}")
print(f"Mean of numbers: {np.mean(numbers)}")

# Exercise: Create a DataFrame with information about different neurons (e.g., type, firing rate)

Array: [1 2 3 4 5]
Mean of array: 3.0
Mean of numbers: 4.8


# Exercise: Create a NumPy array of your own and calculate its standard deviation
# Hint: Google "numpy standard deviation" and look at the examples section on the numpy website. All programmers do this all the time!


In [ ]:
def calculate_standard_deviation(numbers):
  standard_deviation_of_array =
  return standard_deviation_of_array

# Core of Numpy - matrix multiplication!

In [ ]:
matrix_1 = np.array([[1, 2], [3, 4]])
matrix_2 = np.array([[5, 6], [7, 8]])

# Matrix multiplication
result = matrix_1 @ matrix_2

# Element-wise multiplication
elementwise_result = matrix_1 * matrix_2
print("Matrix 1:")
print(matrix_1)
print("Matrix 2:")
print(matrix_2)
print("Matrix Mult. Result")
print(result)
print("Element-wise Mult. Result")
print(elementwise_result)

Matrix 1:
[[1 2]
 [3 4]]
Matrix 2:
[[5 6]
 [7 8]]
Matrix Mult. Result
[[19 22]
 [43 50]]
Element-wise Mult. Result
[[ 5 12]
 [21 32]]


### 2.2 Pandas DataFrames


In [ ]:
# Pandas DataFrames are great for handling "tabular" data
data = {'Name': ['Alice', 'Bob', 'Charlie'],
        'Age': [25, 30, 35],
        'City': ['New York', 'San Francisco', 'Los Angeles']}
df = pd.DataFrame(data)
print(df)

      Name  Age           City
0    Alice   25       New York
1      Bob   30  San Francisco
2  Charlie   35    Los Angeles


In [ ]:
print(df["Name"])

0      Alice
1        Bob
2    Charlie
Name: Name, dtype: object


# Exercise- calculate the mean age of the group of friends